# Docker Compose para Sistema de Análise Logística
version: '3.8'

services:
  # Aplicação principal
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: braslog-app
    ports:
      - "3000:3000"
    environment:
      # Variáveis de ambiente da aplicação
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - braslog-network

  # Nginx como reverse proxy (opcional para produção)
  nginx:
    image: nginx:alpine
    container_name: braslog-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - braslog-network
    profiles:
      - production

networks:
  braslog-network:
    driver: bridge

# Volumes para persistência (se necessário no futuro)
volumes:
  nginx_logs:
    driver: local