# Docker Compose para desenvolvimento local
version: '3.8'

services:
  # Aplicação em modo desenvolvimento
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: braslog-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      # Mount do código para hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - braslog-dev-network
    command: npm run dev

  # PostgreSQL local para desenvolvimento (opcional)
  postgres-dev:
    image: postgres:15-alpine
    container_name: braslog-postgres-dev
    environment:
      - POSTGRES_DB=braslog_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - braslog-dev-network
    profiles:
      - local-db

networks:
  braslog-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local